const pages=[['overview','Vue d’ensemble','⌂'],['prepare','Préparer','✓'],['live','Live','●'],['planning','Planning','▣'],['deck','Control Deck','⌘'],['fun','Fun Deck','✦'],['diagnostics','Diagnostics','◫'],['settings','Réglages','⚙']];
let page='overview',state;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(url,method='GET',body){const response=await fetch(url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw Error(value.error);return value}
async function command(type,details={}){try{state=await request('/api/commands','POST',{type,...details});render();toast('Commande exécutée')}catch(e){toast(e.message,true)}}
async function refresh(){state=await request('/api/state');render()}
function toast(text,bad=false){const el=$('#toast');el.textContent=text;el.className=bad?'show bad':'show';setTimeout(()=>el.className='',2200)}
function duration(seconds){const s=Math.max(0,seconds||0);return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function date(value){return new Date(value).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'})}
function card(label,value,sub='',wide=''){return`<article class="card ${wide}"><span class="label">${label}</span><strong class="metric">${value}</strong><small>${sub}</small></article>`}
function nav(){$('nav').innerHTML=pages.map(([id,label,icon])=>`<button data-page="${id}" class="${id===page?'active':''}"><span>${icon}</span>${label}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;nav();render()})}
function overview(){const next=state.nextLive,done=state.checklist.filter(x=>x.done).length;return`<div class="hero"><div><span class="kicker">BONJOUR, ${esc(state.settings.streamerName).toUpperCase()}</span><h2>${state.obs.streaming?'Le direct est en cours.':'Prêt à lancer votre prochain live ?'}</h2><p>${next?`${esc(next.title)} · ${date(next.startAtUtc)}`:'Ajoutez votre prochain live au planning.'}</p></div><button class="primary big" onclick="go('prepare')">Préparer le live <b>→</b></button></div><div class="grid stats">${card('OBS',state.obs.connected?'Connecté':'Hors ligne',state.obs.scene||'Mode autonome')}${card('Diffusion',state.obs.streaming?'EN DIRECT':'HORS LIGNE',state.obs.recording?'Enregistrement actif':'Aucun enregistrement')}${card('Préparation',`${done}/${state.checklist.length}`,done===state.checklist.length?'Tout est prêt':'Éléments validés')}${card('Timer',duration(state.timer.remaining),state.timer.running?'Compte à rebours actif':'En attente')}</div><div class="section-head"><div><span class="label">ACCÈS RAPIDE</span><h3>Piloter sans quitter le cockpit</h3></div></div><div class="quick"><button onclick="go('live')"><i>●</i><b>Console Live</b><small>Diffusion, timer et séquences</small></button><button onclick="go('deck')"><i>⌘</i><b>Control Deck</b><small>Scènes et audio OBS</small></button><button onclick="go('planning')"><i>▣</i><b>Planning</b><small>Organiser les prochains lives</small></button></div>`}
function prepare(){const done=state.checklist.filter(x=>x.done).length;return`<div class="panel"><div class="section-head"><div><span class="label">CHECKLIST AVANT LIVE</span><h3>${done}/${state.checklist.length} vérifications terminées</h3></div><button class="ghost compact" onclick="command('checklist.reset')">Réinitialiser</button></div><div class="progress"><i style="width:${done/state.checklist.length*100}%"></i></div><div class="checklist">${state.checklist.map(x=>`<button class="check ${x.done?'done':''}" onclick="command('checklist.toggle',{id:'${x.id}'})"><i>${x.done?'✓':''}</i><span><b>${esc(x.label)}</b><small>${x.done?'Validé':'À vérifier'}</small></span></button>`).join('')}</div><div class="launch"><div><b>${done===state.checklist.length?'Tout est prêt':'Préparation incomplète'}</b><small>${state.obs.connected?'OBS répond correctement.':'OBS est hors ligne : connectez-le avant de diffuser.'}</small></div><button class="primary" ${!state.obs.connected?'disabled':''} onclick="command('obs.stream',{start:true})">Démarrer le live</button></div></div>`}
function live(){return`<div class="live-console"><div class="timer-block"><span class="label">TIMER DE SESSION</span><strong>${duration(state.timer.remaining)}</strong><div class="button-row"><button class="primary" onclick="command('${state.timer.running?'timer.pause':'timer.start'}')">${state.timer.running?'Pause':'Démarrer'}</button><button class="ghost" onclick="command('timer.add',{seconds:300})">+ 5 min</button><button class="ghost" onclick="command('timer.reset')">Reset</button></div></div><div class="panel"><span class="label">ÉTAT DU DIRECT</span><h3>${state.obs.streaming?'Vous êtes en direct':'Diffusion arrêtée'}</h3><p class="muted">Scène active : <b>${esc(state.obs.scene||'Aucune')}</b></p><div class="mode-row">${['intro','live','pause','end'].map(x=>`<button class="mode ${state.mode===x?'active':''}" onclick="command('mode.set',{mode:'${x}'})">${x}</button>`).join('')}</div><button class="danger full-button" onclick="stopStream()">${state.obs.streaming?'Arrêter la diffusion':'Diffusion inactive'}</button></div></div>`}
function planning(){return`<div class="section-head"><div><span class="label">CALENDRIER LOCAL</span><h3>Prochains rendez-vous</h3></div><button class="primary compact" onclick="openEvent()">+ Ajouter</button></div><div class="schedule">${state.planning.sort((a,b)=>Date.parse(a.startAtUtc)-Date.parse(b.startAtUtc)).map(x=>`<article><time><b>${new Date(x.startAtUtc).toLocaleDateString('fr-FR',{day:'2-digit'})}</b>${new Date(x.startAtUtc).toLocaleDateString('fr-FR',{month:'short'})}</time><div><span class="tag">${x.category}</span><h3>${esc(x.title)}</h3><p>${date(x.startAtUtc)} — ${date(x.endAtUtc)}</p></div><button class="icon-btn" onclick="removeEvent('${x.id}')">×</button></article>`).join('')||'<div class="empty"><b>Aucun événement planifié</b><p>Votre planning autonome est prêt à accueillir un premier live.</p></div>'}</div><dialog id="event-dialog"><form id="event-form"><div class="section-head"><h3>Nouveau rendez-vous</h3><button type="button" class="icon-btn" onclick="this.closest(\'dialog\').close()">×</button></div><label>Titre<input name="title" required></label><div class="form-grid"><label>Début<input name="start" type="datetime-local" required></label><label>Fin<input name="end" type="datetime-local" required></label></div><label>Type<select name="category"><option value="live">Live</option><option value="production">Production</option><option value="personal">Personnel</option></select></label><button class="primary" type="submit">Enregistrer</button></form></dialog>`}
function deck(){const o=state.obs;return`<div class="section-head"><div><span class="label">OBS WEBSOCKET</span><h3>Scènes</h3></div><span class="status ${o.connected?'ok':''}">${o.connected?'Connecté':'Indisponible'}</span></div><div class="deck">${o.scenes.map(x=>`<button class="pad ${o.scene===x?'active':''}" onclick="command('obs.scene',{scene:decodeURIComponent('${encodeURIComponent(x)}')})"><i>▣</i><b>${esc(x)}</b></button>`).join('')||'<div class="empty">Lancez OBS pour charger vos scènes.</div>'}</div><div class="section-head space"><h3>Mixeur audio</h3></div><div class="mixer">${Object.entries(o.inputs).map(([name,input])=>`<article><button class="mute ${input.muted?'muted':''}" onclick="command('obs.mute',{input:decodeURIComponent('${encodeURIComponent(name)}'),muted:${!input.muted}})">◉</button><div><b>${esc(name)}</b><input type="range" min="0" max="1.5" step=".05" value="${input.volume}" onchange="command('obs.volume',{input:decodeURIComponent('${encodeURIComponent(name)}'),volume:+this.value})"></div><span>${Math.round(input.volume*100)}%</span></article>`).join('')||'<p class="muted">Aucune source audio détectée.</p>'}</div>`}
function fun(){return`<div class="section-head"><div><span class="label">FUN DECK</span><h3>Réactions instantanées</h3></div></div><div class="deck fun">${[['👏','Applaudissements'],['🥁','Roulement'],['✨','Confettis'],['😂','Rire'],['🚨','Alerte'],['💜','Merci !']].map(([icon,label])=>`<button class="pad" onclick="toast('${label} déclenché')"><i>${icon}</i><b>${label}</b><small>Emplacement programmable</small></button>`).join('')}</div>`}
function diagnostics(){return`<div class="grid">${Object.entries(state.health).map(([name,h])=>card(name,`<span class="${h.ok?'green':'red'}">${h.ok?'Opérationnel':'Attention'}</span>`,esc(h.detail))).join('')}</div><div class="panel space"><span class="label">INFORMATIONS TECHNIQUES</span><div class="details"><span>Dernière mise à jour <b>${date(state.at)}</b></span><span>Reconnexions OBS <b>${state.health.obs.reconnects}</b></span><span>API locale <b>127.0.0.1</b></span></div></div>`}
function settings(){return`<form class="panel settings" id="settings-form"><span class="label">PRÉFÉRENCES DU COCKPIT</span><label>Nom affiché<input name="streamerName" value="${esc(state.settings.streamerName)}"></label><label>Couleur d’accent<select name="accent"><option value="violet">Violet</option><option value="cyan">Cyan</option><option value="rose">Rose</option></select></label><label class="switch"><span><b>Confirmer l’arrêt du live</b><small>Évite les arrêts accidentels</small></span><input name="confirmStop" type="checkbox" ${state.settings.confirmStop?'checked':''}></label><label>Adresse OBS WebSocket<input value="${esc(state.settings.obsUrl)}" disabled><small>Modifiable avec OBS_URL dans le fichier .env.</small></label><button class="primary" type="submit">Enregistrer les réglages</button></form>`}
function render(){if(!state)return;document.documentElement.dataset.accent=state.settings.accent;$('#title').textContent=pages.find(x=>x[0]===page)[1];$('#obs-pill').textContent=`OBS ${state.obs.connected?'CONNECTÉ':'HORS LIGNE'}`;$('#obs-pill').className=`obs-pill ${state.obs.connected?'ok':''}`;$('#live-pill').textContent=state.obs.streaming?'● EN DIRECT':'HORS LIGNE';$('#live-pill').className=`live-pill ${state.obs.streaming?'on':''}`;const views={overview,prepare,live,planning,deck,fun,diagnostics,settings};$('#view').innerHTML=views[page]();bindForms()}
function bindForms(){const ef=$('#event-form');if(ef)ef.onsubmit=async e=>{e.preventDefault();const f=new FormData(ef);try{state=await request('/api/planning','POST',{title:f.get('title'),startAtUtc:new Date(f.get('start')).toISOString(),endAtUtc:new Date(f.get('end')).toISOString(),category:f.get('category')});render()}catch(x){toast(x.message,true)}};const sf=$('#settings-form');if(sf){sf.elements.accent.value=state.settings.accent;sf.onsubmit=async e=>{e.preventDefault();const f=new FormData(sf);state=await request('/api/settings','PUT',{streamerName:f.get('streamerName'),accent:f.get('accent'),confirmStop:f.get('confirmStop')==='on'});render();toast('Réglages enregistrés')}}}
window.command=command;window.go=id=>{page=id;nav();render()};window.openEvent=()=>$('#event-dialog').showModal();window.removeEvent=async id=>{state=await request(`/api/planning/${id}`,'DELETE');render()};window.stopStream=()=>{if(!state.obs.streaming)return;if(!state.settings.confirmStop||confirm('Arrêter réellement la diffusion ?'))command('obs.stream',{start:false})};
function socket(){const ws=new WebSocket(`ws://${location.host}/ws`);ws.onopen=()=>{$('#socket').innerHTML='<i></i> Temps réel';$('#socket').classList.add('online')};ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==='state.updated'){state=event.data;render()}};ws.onclose=()=>{ $('#socket').textContent='Reconnexion…';setTimeout(socket,1500)}}
nav();await refresh();socket();
