import { describe, expect, it, vi } from 'vitest';
import { createGoogleOAuthAttempt, GoogleCalendarClient } from '../integrations/google-calendar/src/client.js';
import { TwitchPreflight } from '../integrations/twitch/src/preflight.js';
import { PlanningOrchestrator, type PlanningProvider } from '../packages/core/src/planning.js';
import { RemoteAuth } from '../apps/server/src/remote-auth.js';

const event = { title: 'Counter-Strike 2', startAtUtc: '2030-01-01T10:00:00.000Z', endAtUtc: '2030-01-01T11:00:00.000Z', category: 'live' as const };
const provider = (): PlanningProvider & { create: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn>; delete: ReturnType<typeof vi.fn> } => ({ create: vi.fn(async () => ({ id: crypto.randomUUID(), revision: '1' })), update: vi.fn(async () => ({ revision: '2' })), delete: vi.fn(async () => undefined) });
describe('planning multi-provider', () => {
  it('isole local, Twitch et Google et reste idempotent', async () => { const twitch = provider(), google = provider(), saved: unknown[] = []; const planning = new PlanningOrchestrator([], { twitch, google }, async rows => { saved.push(structuredClone(rows)); }); await planning.create({ ...event, desiredPublication: { local: true, twitch: false, google: false } }); expect(twitch.create).not.toHaveBeenCalled(); const both = await planning.create({ ...event, desiredPublication: { local: true, twitch: true, google: true } }); expect(twitch.create).toHaveBeenCalledOnce(); expect(google.create).toHaveBeenCalledOnce(); await planning.retry(both.id, 'twitch'); await planning.retry(both.id, 'twitch'); expect(twitch.create).toHaveBeenCalledOnce(); expect(twitch.update).toHaveBeenCalledTimes(2); expect(saved.length).toBeGreaterThan(3); });
  it('conserve le succès Google quand Twitch échoue et détecte conflits/suppression', async () => { const twitch = provider(), google = provider(); twitch.create.mockRejectedValue(new Error('Twitch down')); const planning = new PlanningOrchestrator([], { twitch, google }, async () => undefined); const item = await planning.create({ ...event, desiredPublication: { local: true, twitch: true, google: true } }); expect(item.providers?.twitch?.status).toBe('error'); expect(item.providers?.google?.status).toBe('synced'); await planning.markConflict(item.id, 'google', { ...event }); expect(planning.all()[0].conflict?.provider).toBe('google'); await planning.markRemoteDeleted(item.id, 'google'); expect(planning.all()[0].providers?.google?.deletedRemotely).toBe(true); });
});
describe('Google Calendar OAuth et CRUD', () => {
  it('produit PKCE, refuse state invalide et ne persiste que via secret callback', async () => { const attempt = createGoogleOAuthAttempt('client', 'http://127.0.0.1/callback'); expect(new URL(attempt.authorizationUrl).searchParams.get('code_challenge_method')).toBe('S256'); const persist = vi.fn(); const client = new GoogleCalendarClient('client', null, persist, vi.fn()); await expect(client.exchangeCode('code', 'bad', attempt)).rejects.toThrow('invalide'); expect(persist).not.toHaveBeenCalled(); });
  it('utilise la propriété privée idempotente', async () => { const request = vi.fn(async (_url: string, init?: RequestInit) => new Response(JSON.stringify({ id: 'g1', etag: 'e1', summary: 'Live', start: { dateTime: event.startAtUtc }, end: { dateTime: event.endAtUtc }, extendedProperties: { private: { streamDashboardId: 'local-1' } } }), { status: 200, headers: { 'content-type': 'application/json' } })); const client = new GoogleCalendarClient('client', { accessToken: 'a', refreshToken: 'r', expiresAt: Date.now() + 60_000 }, async () => undefined, request as typeof fetch); await client.create('primary', { localId: 'local-1', ...event }); expect(String(request.mock.calls[0][1]?.body)).toContain('streamDashboardId'); });
});
describe('preflight et télécommande', () => {
  it('prépare titre/game id une fois et ne démarre jamais OBS', async () => { const api = { getChannel: vi.fn(async () => ({ title: 'ancien', gameId: '0' })), searchGame: vi.fn(async () => [{ id: '32399', name: 'Counter-Strike 2' }]), updateChannel: vi.fn(async () => undefined) }; const preflight = new TwitchPreflight(api); expect((await preflight.prepare({ eventId: '1', title: event.title, category: 'live' })).status).toBe('action-required'); await preflight.prepare({ eventId: '1', title: event.title, category: event.title }); api.getChannel.mockResolvedValue({ title: event.title, gameId: '32399' }); await preflight.prepare({ eventId: '1', title: event.title, category: event.title }); expect(api.updateChannel).toHaveBeenCalledOnce(); });
  it('pairing est aléatoire, à usage unique, expirant, révocable et limité', () => { let now = 10; const auth = new RemoteAuth(() => now); const pairing = auth.createPairing(100); const device = auth.pair(pairing.id, pairing.code, 'Pixel'); expect(auth.authenticate(device.credential)).toBe(device.deviceId); expect(() => auth.pair(pairing.id, pairing.code, 'Replay')).toThrow(); auth.revoke(device.deviceId); expect(auth.authenticate(device.credential)).toBeNull(); const expired = auth.createPairing(1); now = 20; expect(() => auth.pair(expired.id, expired.code, 'Late')).toThrow(); });
});
