import { describe, expect, it, vi } from 'vitest';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { assertSecretFree, defaultProductProfile, exportProductProfile, importProductProfile, validateProductProfile } from '../packages/core/src/product-profile.js';
import { resolveModules, setModule } from '../packages/core/src/module-registry.js';
import { ConnectionRegistry, connectionStatusLabels, type ConnectionProvider } from '../packages/core/src/connection-provider.js';
import { ProductProfileStore } from '../apps/server/src/profile-store.js';
describe('profil StreamDashboard YAML', () => {
  it('round-trip un vrai YAML versionné sans secret', () => { const initial = defaultProductProfile(); const yaml = exportProductProfile(initial); expect(yaml).toMatch(/^version: 1\nprofile:\n  displayName:/); expect(yaml.trimStart()).not.toMatch(/^\{/); expect(importProductProfile(yaml)).toEqual(initial); });
  it('importe, valide, exporte et réimporte le YAML réel du dépôt', async () => { const source = await readFile(new URL('../streamdashboard.yaml', import.meta.url), 'utf8'); const profile = importProductProfile(source); expect(profile.version).toBe(1); const exported = exportProductProfile(profile); expect(exported).toMatch(/^version: 1\n/); expect(importProductProfile(exported)).toEqual(profile); });
  it('rejette corruption, clés dupliquées, versions futures et secrets imbriqués', () => { expect(() => importProductProfile('not yaml')).toThrow(/Import impossible/); expect(() => importProductProfile('version: 1\nversion: 1')).toThrow(/dupliquée/); expect(() => validateProductProfile({ version: 2 })).toThrow(/Version/); expect(() => assertSecretFree({ obs: { password: 'nope' } })).toThrow(/secret/i); });
  it('migre un profil v0 sans toucher aux données Runtime historiques', () => { const migrated = importProductProfile('version: 0\nprofile:\n  displayName: \"Ancien streamer\"\n'); expect(migrated.version).toBe(1); expect(migrated.profile.displayName).toBe('Ancien streamer'); });
  it('valide les couleurs', () => { const profile = defaultProductProfile(); profile.appearance.accent = 'red'; expect(() => validateProductProfile(profile)).toThrow(/#RRGGBB/); });
  it('persiste, sauvegarde les imports et récupère un fichier corrompu', async () => { const dir = await mkdtemp(path.join(os.tmpdir(), 'streamdashboard-profile-')); const file = path.join(dir, 'streamdashboard.yaml'); try { const store = new ProductProfileStore(file); const created = await store.load(); created.profile.displayName = 'Alice'; await store.save(created); const imported = defaultProductProfile(); imported.profile.displayName = 'Bob'; const result = await store.import(exportProductProfile(imported)); expect(result.backup).toBeTruthy(); expect((await store.load()).profile.displayName).toBe('Bob'); expect((await readFile(result.backup!, 'utf8'))).toContain('Alice'); await writeFile(file, 'bad yaml'); expect((await store.load()).profile.displayName).toBe('Streamer'); } finally { await rm(dir, { recursive: true, force: true }); } });
});
describe('modules produit', () => { it('refuse un profil incohérent avec une explication', () => { const profile = defaultProductProfile(); profile.modules.twitch = false; expect(() => validateProductProfile(profile)).toThrow(/streamerPings nécessite/); }); it('active les dépendances et désactive leurs enfants', () => { let profile = defaultProductProfile(); profile = setModule(profile, 'twitch', false); expect(profile.modules.streamerPings).toBe(false); profile = setModule(profile, 'streamerPings', true); expect(profile.modules.twitch).toBe(true); expect(resolveModules(profile).find(item => item.id === 'streamerPings')?.blockedBy).toEqual([]); }); });
describe('connexions unifiées', () => { it('expose le contrat et les libellés communs', async () => { const provider: ConnectionProvider = { id: 'obs', label: 'OBS', capabilities: ['test'], connect: vi.fn(), disconnect: vi.fn(), test: vi.fn(), refresh: vi.fn(), requiresReauth: vi.fn(async () => false), getStatus: vi.fn(async () => ({ id: 'obs', label: 'OBS', status: 'connected' as const, mode: 'custom' as const, capabilities: ['test'], requiresReauth: false })) }; const registry = new ConnectionRegistry().register(provider); expect((await registry.statuses())[0].status).toBe('connected'); expect(connectionStatusLabels['reauth-required']).toBe('Autorisation nécessaire'); expect(() => registry.register(provider)).toThrow(/déjà/); }); });
