import { describe, expect, it, vi } from 'vitest';
import { CompanionMode, createCompanionStore } from '../apps/mobile/companion-store.js';
import { createStandaloneProviderSync, twitchFingerprint } from '../apps/mobile/provider-sync.js';
class Memory { data=new Map<string,string>(); getItem(k:string){return this.data.get(k)||null;} setItem(k:string,v:string){this.data.set(k,v);} }
const setup=()=>{const store=createCompanionStore(new Memory() as unknown as Storage,()=> '2026-09-13T00:00:00Z');const event=store.createEvent({id:'X',title:'FC26',startAtUtc:'2026-09-19T21:00:00Z',endAtUtc:'2026-09-19T23:00:00Z',desiredPublication:{twitch:true,google:true}}).item!;const adapter={mutate:vi.fn(),searchTwitch:vi.fn()};return{store,event,adapter,sync:createStandaloneProviderSync({store,adapter})};};
describe('routage providers autonomes',()=>{
 it.each([CompanionMode.ONLINE_PC,CompanionMode.OFFLINE])('n’appelle aucun provider direct en %s',async mode=>{const {sync,event,adapter}=setup();await sync.apply(mode,event,'create');expect(adapter.mutate).not.toHaveBeenCalled();});
 it('publie chaque provider et garde eventId et IDs distants',async()=>{const {sync,event,adapter,store}=setup();adapter.mutate.mockImplementation(async(p:string)=>({remoteId:`${p}-remote`,revision:'etag'}));await sync.apply(CompanionMode.ONLINE_STANDALONE,event,'create');expect(adapter.mutate).toHaveBeenCalledTimes(2);expect(store.snapshot().planning[0]).toMatchObject({id:'X',providerLinks:{twitch:{status:'synced',remoteId:'twitch-remote'},google:{status:'synced',remoteId:'google-remote'}}});});
 it('conserve un succès partiel et retry Google seulement',async()=>{const {sync,event,adapter,store}=setup();adapter.mutate.mockImplementation(async(p:string)=>{if(p==='google')throw new Error('réseau');return{remoteId:'tw-1'};});await sync.apply(CompanionMode.ONLINE_STANDALONE,event,'create');let current=store.snapshot().planning[0];expect(current.providerLinks).toMatchObject({twitch:{status:'synced'},google:{status:'error'}});adapter.mutate.mockResolvedValue({remoteId:'g-1'});await sync.apply(CompanionMode.ONLINE_STANDALONE,current,'create','google');expect(adapter.mutate).toHaveBeenCalledTimes(3);expect(store.snapshot().planning[0].providerLinks.google.status).toBe('synced');});
 it('conserve un conflit provider explicite',async()=>{const {sync,event,adapter,store}=setup();adapter.mutate.mockRejectedValue(Object.assign(new Error('changé'),{code:'CONFLICT',current:{title:'ailleurs'}}));await sync.apply(CompanionMode.ONLINE_STANDALONE,event,'update','twitch');expect(store.snapshot().planning[0].providerLinks.twitch).toMatchObject({status:'conflict',remoteSnapshot:{title:'ailleurs'}});});
 it('route catégories strictement',async()=>{const {sync,adapter}=setup();const pc=vi.fn().mockResolvedValue([{id:'pc'}]);adapter.searchTwitch.mockResolvedValue([{id:'native'}]);expect(await sync.searchCategories(CompanionMode.ONLINE_PC,'fc',[],pc)).toEqual([{id:'pc'}]);expect(await sync.searchCategories(CompanionMode.ONLINE_STANDALONE,'fc',[],pc)).toEqual([{id:'native'}]);expect(await sync.searchCategories(CompanionMode.OFFLINE,'fc',[{id:'recent'}],pc)).toEqual([{id:'recent'}]);});
 it('fingerprint Twitch stable',()=>{expect(twitchFingerprint({title:'A',startAtUtc:'20'})).toBe(twitchFingerprint({title:'A',startAtUtc:'20'}));expect(twitchFingerprint({title:'A',startAtUtc:'20'})).not.toBe(twitchFingerprint({title:'A',startAtUtc:'21'}));});
});
