import express from'express';import{createServer}from'node:http';import{WebSocketServer}from'ws';import QRCode from'qrcode';import{DamPlannerClient,nextLive}from'../../../integrations/damplanner/src/client.js';import{StreamToolClient,type StreamAction}from'../../../integrations/streamtool/src/client.js';import{ObsClient}from'../../../integrations/obs/src/client.js';import{PairingStore}from'../../../packages/auth/src/pairing.js';import type{DashboardState}from'../../../packages/contracts/src/index.js';import path from'node:path';
const app=express(),server=createServer(app),wss=new WebSocketServer({noServer:true}),planner=new DamPlannerClient(),stream=new StreamToolClient(),obs=new ObsClient(),pairing=new PairingStore();const port=Number(process.env.PORT??47832);let state:DashboardState={at:new Date().toISOString(),streamTool:null,planning:null,obs:obs.state,nextLive:null,unscheduledLive:false,health:{dashboard:{ok:true,reconnects:0},streamTool:{ok:false,reconnects:0},damPlanner:{ok:false,reconnects:0},obs:{ok:false,reconnects:0},mobile:{ok:true,reconnects:0}}};let lastErrors:string[]=[];
app.use(express.json({limit:'16kb'}));app.use(express.static(path.resolve('apps/web')));
const attempts=new Map<string,{at:number,count:number}>();app.use('/api',(req,res,next)=>{const key=req.ip??'unknown',now=Date.now(),x=attempts.get(key);if(!x||now-x.at>60_000)attempts.set(key,{at:now,count:1});else if(++x.count>120)return res.status(429).json({error:'Trop de requêtes'});next()});
function auth(req:express.Request,res:express.Response,next:express.NextFunction){const id=req.get('x-device-id')??'',token=req.get('authorization')?.replace(/^Bearer /,'')??'';if(req.ip==='127.0.0.1'||req.ip==='::1'||pairing.authenticate(id,token))return next();res.status(401).json({error:'Appareil non autorisé'})}
async function aggregate(refresh=false){const results=await Promise.allSettled([stream.state(),planner.calendar(refresh),obs.refresh()]);const names=['streamTool','damPlanner','obs'];results.forEach((r,i)=>{const h=state.health[names[i]!]!;h.ok=r.status==='fulfilled';if(r.status==='rejected'){h.error=String(r.reason);lastErrors=[`${new Date().toISOString()} ${names[i]}: ${r.reason}`,...lastErrors].slice(0,20)}else delete h.error});if(results[0]?.status==='fulfilled')state.streamTool=results[0].value;if(results[1]?.status==='fulfilled')state.planning=results[1].value;state.obs=obs.state;state.health.obs!.reconnects=obs.reconnectCount;state.nextLive=nextLive(state.planning?.items??[]);state.unscheduledLive=Boolean((state.obs.streaming||state.streamTool?.obs.streaming)&&!state.nextLive);state.at=new Date().toISOString();broadcast();return state}
function broadcast(){const data=JSON.stringify({type:'state',data:state});for(const ws of wss.clients)if(ws.readyState===1)ws.send(data)}
app.get('/api/state',async(_q,r)=>r.json(await aggregate()));app.post('/api/planning/refresh',auth,async(_q,r)=>r.json(await aggregate(true)));app.post('/api/stream/:action',auth,async(req,r)=>{const action=req.params.action as StreamAction;const value=action==='cancelEnd'?await stream.cancelEnd():await stream.action(action);await aggregate();r.json(value)});app.post('/api/timer/:action',auth,async(req,r)=>{const value=await stream.timer(req.params.action as never,req.body?.seconds);await aggregate();r.json(value)});app.post('/api/obs/scene',auth,async(req,r)=>{await obs.scene(String(req.body.scene));await aggregate();r.json(state.obs)});app.post('/api/obs/mute',auth,async(req,r)=>{await obs.mute(String(req.body.input),Boolean(req.body.muted));await aggregate();r.json(state.obs)});app.post('/api/obs/volume',auth,async(req,r)=>{await obs.volume(String(req.body.input),Number(req.body.volume));r.json({ok:true})});app.post('/api/obs/stream',auth,async(req,r)=>{await obs.stream(Boolean(req.body.start));await aggregate();r.json(state.obs)});
app.post('/api/pair/code',auth,async(_q,r)=>{const code=pairing.issueCode(),url=`${process.env.PUBLIC_URL??`http://127.0.0.1:${port}`}/?pair=${code}`;r.json({code,url,qr:await QRCode.toDataURL(url)})});app.post('/api/pair', (req,r)=>{try{r.json(pairing.pair(String(req.body.code),String(req.body.name??'Mobile')))}catch(e){r.status(401).json({error:String(e)})}});app.get('/api/devices',auth,(_q,r)=>r.json(pairing.list()));app.delete('/api/devices/:id',auth,(req,r)=>r.json({revoked:pairing.revoke(String(req.params.id))}));app.get('/api/diagnostics',auth,(_q,r)=>r.json({health:state.health,errors:lastErrors}));
server.on('upgrade',(req,socket,head)=>{const u=new URL(req.url??'/',`http://${req.headers.host}`);if(u.pathname!='/ws'||(!['127.0.0.1','::1'].includes(req.socket.remoteAddress??'')&&!pairing.authenticate(u.searchParams.get('device')??'',u.searchParams.get('token')??'')))return socket.destroy();wss.handleUpgrade(req,socket,head,ws=>{wss.emit('connection',ws,req);ws.send(JSON.stringify({type:'state',data:state}))})});
app.use((e:unknown,_q:express.Request,r:express.Response,_n:express.NextFunction)=>r.status(502).json({error:e instanceof Error?e.message:'Erreur'}));void obs.connect();setInterval(()=>void aggregate(),2000);server.listen(port,'0.0.0.0',()=>console.log(`StreamDashboard http://127.0.0.1:${port}`));
