import { fixture } from './fixtures.js';

const state={
  view:'home',runtime:false,scene:fixture.live.scene,timerRunning:true,seconds:36,
  sounds:structuredClone(fixture.sounds),audio:structuredClone(fixture.audio),live:structuredClone(fixture.live),
  planning:structuredClone(fixture.planning),dashboard:null,soundboard:null,obsSetup:null,search:''
};
const view=document.querySelector('#view'),title=document.querySelector('#title'),eyebrow=document.querySelector('#eyebrow');
const commandLog=[]; window.__preview={state,commandLog};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>globalThis.crypto?.randomUUID?.()||`cmd_${Date.now()}_${Math.random().toString(36).slice(2)}`;
function toast(message,bad=false){const el=document.querySelector('#toast');el.textContent=message;el.classList.toggle('bad',bad);el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
async function request(path,options={}){const response=await fetch(path,{headers:{'content-type':'application/json',...(options.headers||{})},...options});const body=response.status===204?null:await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||body?.error||`HTTP ${response.status}`);return body}
function record(type,payload={}){commandLog.push({type,payload})}
function runtimeUi(online,copy){document.querySelector('#runtime-status').textContent=online?'Runtime PC':'Mode Démo';document.querySelector('#runtime-copy').textContent=copy;document.querySelector('#runtime-dot').classList.toggle('offline',!online)}
const logicalScene=name=>{
  const settings=state.dashboard?.settings||{};
  if(settings.modeScenes?.intro===name)return'Intro';
  if(settings.modeScenes?.live===name)return'Gameplay';
  if(settings.chattingScene===name)return'Chatting';
  if(settings.modeScenes?.pause===name)return'Pause';
  if(settings.modeScenes?.end===name)return'Fin';
  return name;
};
const sceneCommand=label=>({
  Intro:{type:'mode.set',mode:'intro'},Gameplay:{type:'mode.set',mode:'live'},Chatting:{type:'scene.chatting'},
  Pause:{type:'mode.set',mode:'pause'},Fin:{type:'mode.set',mode:'end'}
})[label];
async function dashboardCommand(command,logType='dashboard.command',logPayload=command){
  record(logType,logPayload); if(!state.runtime)return null;
  const commandId=uid();const body=await request('/api/v1/commands',{method:'POST',body:JSON.stringify({...command,commandId,correlationId:commandId})});
  if(body?.state)applyDashboard(body.state);return body;
}
async function refreshRuntime(){
  if(!state.runtime)return;
  try{
    const [dashboard,soundboard,setup]=await Promise.all([
      request('/api/v1/state'),request('/api/v1/soundboard'),request('/api/v1/soundboard/obs/status').catch(()=>null)
    ]);
    applyDashboard(dashboard);state.soundboard=soundboard;state.sounds=soundboard.sounds||[];state.obsSetup=setup;
    runtimeUi(true,dashboard.obs?.connected?'OBS connecté':'Runtime connecté · OBS hors ligne');render();
  }catch(error){runtimeUi(true,'Runtime indisponible');toast(error.message,true)}
}
function applyDashboard(d){
  state.dashboard=d;state.scene=d.obs?.scene||'—';state.timerRunning=d.timer?.running===true;state.seconds=Math.max(0,Math.ceil(Number(d.timer?.remaining)||0));
  const hub=d.controlHub||{};state.live={
    active:hub.live?.isLive===true||d.obs?.streaming===true,
    duration:formatDuration(hub.live?.durationSeconds??0),title:hub.live?.title||d.twitch?.channelTitle||'Prêt à streamer',
    category:hub.live?.category||d.twitch?.gameName||'—',viewers:hub.audience?.viewerCount??'—',chatters:Array.isArray(hub.audience?.chatters)?hub.audience.chatters.length:'—',
    scene:d.obs?.scene||'—'
  };
  const inputs=d.obs?.inputs||{};const active=Array.isArray(d.obs?.activeAudioInputs)?d.obs.activeAudioInputs:Object.keys(inputs);
  state.audio=active.filter(name=>inputs[name]).slice(0,6).map(name=>{const input=inputs[name];const db=Number.isFinite(input.volumeDb)?input.volumeDb:-100;return{name,muted:input.muted,volume:Math.round(Math.max(0,Math.min(1,input.volume??0))*100),level:Math.round(Math.max(0,Math.min(100,((db+60)/66)*100))),primary:d.settings?.primaryMicInput===name}});
  state.planning=(d.planning||[]).filter(item=>Date.parse(item.endAtUtc||item.startAtUtc)>Date.now()).sort((a,b)=>Date.parse(a.startAtUtc)-Date.parse(b.startAtUtc)).slice(0,12).map(item=>{const start=new Date(item.startAtUtc);return{raw:item,day:start.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric'}),time:start.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),title:item.title,kind:item.category==='live'?'Twitch':item.category==='personal'?'Personnel':'Production'}});
}
function formatDuration(seconds){const n=Math.max(0,Math.floor(Number(seconds)||0));return`${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor(n/60)%60).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
const primaryScenes=['Intro','Gameplay','Chatting','Pause','Fin'];
const scenes=()=>`<div class="scene-grid">${primaryScenes.map(name=>`<button class="scene ${logicalScene(state.scene)===name?'active':''}" data-scene="${name}" aria-pressed="${logicalScene(state.scene)===name}">${name}</button>`).join('')}</div>`;
function filteredSounds(){const query=state.search.trim().toLowerCase();return(state.sounds||[]).filter(s=>!query||String(s.name).toLowerCase().includes(query)||String(s.category).toLowerCase().includes(query))}
const sounds=(editable=false)=>Object.entries(filteredSounds().reduce((groups,s)=>{(groups[s.category||'Sans catégorie']??=[]).push(s);return groups},{})).map(([category,items])=>`<div class="group"><h3>${esc(category)}</h3><div class="pads">${items.map(s=>`<div class="sound-item"><button class="pad ${s.sourceAvailable===false?'missing':''}" data-sound="${esc(s.id)}" ${s.enabled===false?'disabled':''}>${esc(s.name)}${s.sourceAvailable===false?' · absent':''}</button>${editable?`<button class="edit-sound" data-edit-sound="${esc(s.id)}" aria-label="Modifier ${esc(s.name)}">•••</button>`:''}</div>`).join('')}</div></div>`).join('');
function home(){return`<div class="stack"><section class="status-strip"><div><span class="live-pill">${state.live.active?'● LIVE':'○ PRÊT'}</span><strong class="value">${esc(state.live.duration)}</strong><span class="label">${esc(state.live.title)} · ${esc(state.live.category)}</span></div><div><span class="label">Viewers</span><b class="value">${esc(state.live.viewers??17)}</b></div><div><span class="label">Chat</span><b class="value">${esc(state.live.chatters??6)}</b></div><div><span class="label">OBS</span><b>${state.runtime?(state.dashboard?.obs?.connected?'Connecté':'Hors ligne'):'Démo'}</b></div><div><span class="label">Twitch</span><b>${state.runtime?(state.dashboard?.twitch?.connected?'Connecté':'Déconnecté'):'Démo'}</b></div></section><section class="section"><div class="section-head"><h2>Scènes principales</h2><span class="label">Active · ${esc(state.scene)}</span></div>${scenes()}</section><section class="section"><div class="section-head"><h2>Sons rapides</h2><button class="secondary" data-add-sound>+ Ajouter un son rapide</button></div><div class="sound-groups">${sounds(false)||'<p class="label">Aucun son.</p>'}</div></section></div>`}
function live(){return`<div class="cockpit"><section class="status-strip wide"><div><span class="live-pill">${state.live.active?'● LIVE':'○ PRÊT'}</span><b class="value">${esc(state.live.duration)}</b></div><div><span class="label">Viewers</span><b class="value">${esc(state.live.viewers??17)}</b></div><div><span class="label">Chat</span><b class="value">${esc(state.live.chatters??6)}</b></div><div><span class="label">Scène</span><b>${esc(state.scene)}</b></div><div><button class="critical" data-live-toggle>${state.live.active?'Arrêter le live':'Démarrer le live'}</button></div></section><section class="section wide"><div class="section-head"><h2>Scènes</h2></div>${scenes()}</section><section class="section"><div class="section-head"><h2>Audio</h2><span class="label">Sources actives</span></div>${state.audio.map((a,i)=>`<div class="audio-row"><b>${esc(a.name)}${a.primary?' · principal':''}</b><button data-mute="${i}" aria-label="${a.muted?'Réactiver':'Couper'} ${esc(a.name)}">${a.muted?'OFF':'ON'}</button><div class="meter"><i style="width:${a.level}%"></i></div><span>${a.volume}%</span></div>`).join('')||'<p class="label">Aucune source audio active.</p>'}</section><section class="section timer"><div class="section-head"><h2>Timer</h2></div><b class="timer-value">${formatDuration(state.seconds)}</b><div class="timer-actions"><button class="action" data-timer="minus">−1 min</button><button class="action" data-timer="toggle">${state.timerRunning?'Pause':'Play'}</button><button class="action" data-timer="plus">+1 min</button><button class="action" data-timer="reset">Reset</button></div></section></div>`}
function soundboard(){const setup=state.obsSetup;const label=state.runtime?(setup?.ready?'OBS Soundboard · prête':setup?.connected?'OBS Soundboard · à configurer':'OBS Soundboard · OBS hors ligne'):'OBS Soundboard · Démo';return`<section class="section"><div class="section-head"><div><h2>Soundboard</h2><span class="label">${label} · une lecture à la fois</span></div><div><button class="secondary" data-obs-setup>Configurer dans OBS</button> <button class="critical" data-stop>Stop</button></div></div><div class="toolbar"><input type="search" value="${esc(state.search)}" placeholder="Rechercher un son" aria-label="Rechercher un son" data-sound-search><button class="action" data-add-sound>+ Ajouter un son</button></div><div class="sound-groups">${sounds(true)||'<p class="label">Bibliothèque vide.</p>'}</div></section>`}
function planning(){return`<section class="section"><div class="section-head"><div><h2>Semaine</h2><span class="label">Planning à venir</span></div><button class="action" data-add-event>+ Nouvel événement</button></div><div class="agenda">${state.planning.map(e=>`<button class="event"><b>${esc(e.day)}</b><span>${esc(e.time)}</span><strong>${esc(e.title)}</strong><span class="kind">${esc(e.kind)}</span></button>`).join('')||'<p class="label">Aucun événement à venir.</p>'}</div></section>`}
const campItems=['Préparation','Notes','Templates','Soutiens','Automatisations','Médias OBS','Connexions','Diagnostics','Réglages'];
function camp(){return`<div class="camp-grid"><section class="section camp-nav">${campItems.map((x,i)=>`<button class="${i===0?'active':''}" data-camp="${x}">${x}</button>`).join('')}</section><section class="section empty-detail"><p class="eyebrow">LE CAMP</p><h2 id="camp-title">Préparation</h2><p id="camp-copy">Checklist avant direct · les outils secondaires restent hors du cockpit principal.</p></section></div>`}
function render(){const names={home:['Accueil','COCKPIT'],live:['Live','EN DIRECT'],sounds:['Sons','BIBLIOTHÈQUE'],planning:['Planning','SEMAINE'],camp:['Le Camp','SECONDAIRE']};[title.textContent,eyebrow.textContent]=names[state.view];view.innerHTML=({home,live,sounds:soundboard,planning,camp}[state.view])();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',b.dataset.view===state.view?'page':'false'));bind()}
async function playSound(soundId){record('soundboard.play',{soundId});if(!state.runtime){toast('Lecture simulée');return}try{const commandId=uid();const ack=await request('/api/v1/soundboard/play',{method:'POST',body:JSON.stringify({commandId,correlationId:commandId,soundId,issuedAt:new Date().toISOString()})});if(ack.status!=='succeeded')throw new Error(ack.message||'Lecture refusée.');toast('Son envoyé à OBS');await refreshRuntime()}catch(error){toast(error.message,true)}}
async function toggleLive(){if(!state.runtime){record(state.live.active?'session.stop':'session.start');state.live.active=!state.live.active;render();return}try{if(state.live.active){if(!confirm('Arrêter réellement le live ?'))return;await dashboardCommand({type:'session.stop'},'session.stop');}else{if(!confirm('Démarrer réellement le live ?'))return;await dashboardCommand({type:'session.prepare'},'session.prepare');try{await dashboardCommand({type:'session.start'},'session.start')}catch(error){if(confirm(`${error.message}\n\nDémarrer quand même ?`))await dashboardCommand({type:'session.start',force:true},'session.start');else throw error}}await refreshRuntime()}catch(error){toast(error.message,true)}}
function bind(){
  document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=async()=>{const label=b.dataset.scene;record('obs.scene.set',{sceneName:label});if(!state.runtime){state.scene=label;toast(`Scène ${label}`);render();return}try{await dashboardCommand(sceneCommand(label));await refreshRuntime();toast(`Scène ${label}`)}catch(error){toast(error.message,true)}});
  document.querySelectorAll('[data-sound]').forEach(b=>b.onclick=()=>void playSound(b.dataset.sound));
  document.querySelectorAll('[data-edit-sound]').forEach(b=>b.onclick=event=>{event.stopPropagation();openSoundDialog(b.dataset.editSound)});
  document.querySelectorAll('[data-mute]').forEach(b=>b.onclick=async()=>{const a=state.audio[+b.dataset.mute];if(!a)return;record('obs.audio.mute',{inputName:a.name,muted:!a.muted});if(!state.runtime){a.muted=!a.muted;render();return}try{await dashboardCommand({type:'obs.mute',input:a.name,muted:!a.muted});await refreshRuntime()}catch(error){toast(error.message,true)}});
  document.querySelectorAll('[data-timer]').forEach(b=>b.onclick=async()=>{const action=b.dataset.timer;record(`timer.${action}`);if(!state.runtime){if(action==='toggle')state.timerRunning=!state.timerRunning;if(action==='plus')state.seconds+=60;if(action==='minus')state.seconds=Math.max(0,state.seconds-60);if(action==='reset'){state.seconds=0;state.timerRunning=false}render();return}const command=action==='toggle'?{type:state.timerRunning?'timer.pause':'timer.start'}:action==='plus'?{type:'timer.add',seconds:60}:action==='minus'?{type:'timer.add',seconds:-60}:{type:'timer.reset'};try{await dashboardCommand(command);await refreshRuntime()}catch(error){toast(error.message,true)}});
  document.querySelector('[data-stop]')?.addEventListener('click',async()=>{record('soundboard.stop');if(!state.runtime){toast('Lecture arrêtée');return}try{await request('/api/v1/soundboard/stop',{method:'POST',body:'{}'});toast('Lecture arrêtée');await refreshRuntime()}catch(error){toast(error.message,true)}});
  document.querySelectorAll('[data-add-sound]').forEach(b=>b.onclick=()=>openSoundDialog());
  document.querySelector('[data-obs-setup]')?.addEventListener('click',()=>void openObsSetup());
  document.querySelector('[data-live-toggle]')?.addEventListener('click',()=>void toggleLive());
  document.querySelector('[data-add-event]')?.addEventListener('click',openEventDialog);
  document.querySelector('[data-sound-search]')?.addEventListener('input',e=>{state.search=e.currentTarget.value;render()});
  document.querySelectorAll('[data-camp]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-camp]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#camp-title').textContent=b.dataset.camp;document.querySelector('#camp-copy').textContent=b.dataset.camp==='Diagnostics'?`Build ${state.dashboard?.runtime?.serverVersion||'Preview'} · stateRevision ${state.dashboard?.stateRevision??'—'}`:'Cet outil reste accessible sans encombrer le cockpit.'});
}
let selectedSoundFile='';
function openSoundDialog(id=''){const sound=(state.sounds||[]).find(s=>s.id===id);selectedSoundFile='';document.querySelector('#sound-id').value=id;document.querySelector('#sound-dialog-title').textContent=sound?'Modifier le son':'Ajouter un son';document.querySelector('#sound-name').value=sound?.name||'';document.querySelector('#sound-category').value=sound?.category||'';document.querySelector('#sound-volume').value=String(Math.round((sound?.volume??1)*100));document.querySelector('#sound-cooldown').value=String(Math.round((sound?.cooldownMs??0)/1000));document.querySelector('#sound-monitoring').value=sound?.monitoringMode||'stream';document.querySelector('#sound-favorite').checked=sound?.favorite===true;document.querySelector('#sound-enabled').checked=sound?.enabled!==false;document.querySelector('#sound-file-copy').textContent=sound?'Conserver le fichier actuel':'Aucun fichier choisi';document.querySelector('#sound-delete').hidden=!sound;document.querySelector('#sound-dialog').showModal()}
document.querySelector('#sound-file-button').onclick=async()=>{if(!window.streamDashboardDesktop?.selectSoundFile)return toast('Sélecteur de fichier indisponible.',true);const file=await window.streamDashboardDesktop.selectSoundFile();if(file){selectedSoundFile=file;document.querySelector('#sound-file-copy').textContent=file.split(/[\\/]/).pop()}};
document.querySelector('#sound-form').onsubmit=async event=>{event.preventDefault();const id=document.querySelector('#sound-id').value;const metadata={name:document.querySelector('#sound-name').value.trim(),category:document.querySelector('#sound-category').value.trim(),volume:Number(document.querySelector('#sound-volume').value)/100,cooldownMs:Math.round(Number(document.querySelector('#sound-cooldown').value)*1000),monitoringMode:document.querySelector('#sound-monitoring').value,favorite:document.querySelector('#sound-favorite').checked,enabled:document.querySelector('#sound-enabled').checked};if(!state.runtime){const existing=state.sounds.find(s=>s.id===id);if(existing)Object.assign(existing,metadata);else state.sounds.push({id:`demo-${Date.now()}`,...metadata,sourceAvailable:true});document.querySelector('#sound-dialog').close();render();return}try{let libraryId;if(selectedSoundFile){const imported=await window.streamDashboardDesktop.importSoundFile(selectedSoundFile);libraryId=imported.libraryId}if(!id&&!libraryId)throw new Error('Choisissez un fichier audio.');const body={...metadata,...(libraryId?{libraryId}:{})};state.soundboard=await request(id?`/api/v1/soundboard/sounds/${encodeURIComponent(id)}`:'/api/v1/soundboard/sounds',{method:id?'PUT':'POST',body:JSON.stringify(body)});state.sounds=state.soundboard.sounds||[];document.querySelector('#sound-dialog').close();toast('Soundboard enregistrée');render()}catch(error){toast(error.message,true)}};
document.querySelector('#sound-delete').onclick=async()=>{const id=document.querySelector('#sound-id').value;if(!id)return;if(!confirm('Supprimer ce son de la Soundboard ?'))return;if(!state.runtime){state.sounds=state.sounds.filter(s=>s.id!==id);document.querySelector('#sound-dialog').close();render();return}try{await request(`/api/v1/soundboard/sounds/${encodeURIComponent(id)}`,{method:'DELETE'});document.querySelector('#sound-dialog').close();await refreshRuntime();toast('Son supprimé')}catch(error){toast(error.message,true)}};
async function openObsSetup(){document.querySelector('#obs-setup-dialog').showModal();const host=document.querySelector('#obs-setup-status');if(!state.runtime){host.innerHTML='<p><b>Démo</b></p><p>Créera ou réparera la Media Source « StreamDashboard • Soundboard » dans Intro, Gameplay, Chatting, Pause et Fin.</p>';return}host.textContent='Vérification OBS…';try{state.obsSetup=await request('/api/v1/soundboard/obs/status');renderObsSetupStatus()}catch(error){host.textContent=error.message}}
function renderObsSetupStatus(){const s=state.obsSetup,host=document.querySelector('#obs-setup-status');if(!s){host.textContent='État indisponible.';return}host.innerHTML=`<p><b>${s.ready?'Prêt':'Configuration requise'}</b></p><p>Source : ${esc(s.inputExists?s.inputName:'à créer')}</p><p>Scènes cibles : ${esc(s.targetScenes.join(', ')||'aucune')}</p><p>Déjà raccordées : ${esc(s.attachedScenes.join(', ')||'aucune')}</p>${s.missingScenes.length?`<p class="warning">Scènes configurées absentes d’OBS : ${esc(s.missingScenes.join(', '))}</p>`:''}${s.wrongInputKind?'<p class="warning">Une source du même nom existe avec un type incompatible.</p>':''}`}
document.querySelector('#obs-setup-form').onsubmit=async event=>{event.preventDefault();if(!state.runtime)return toast('Passe en mode Runtime pour modifier OBS.');try{state.obsSetup=await request('/api/v1/soundboard/obs/setup',{method:'POST',body:'{}'});renderObsSetupStatus();toast(state.obsSetup.ready?'Soundboard OBS prête':'Réparation partielle terminée')}catch(error){toast(error.message,true);await openObsSetup()}};
function openEventDialog(){const date=new Date();document.querySelector('#event-date').value=date.toISOString().slice(0,10);document.querySelector('#event-dialog').showModal()}
document.querySelector('#event-form').onsubmit=async event=>{event.preventDefault();const date=document.querySelector('#event-date').value,start=document.querySelector('#event-start').value,end=document.querySelector('#event-end').value;const startAtUtc=new Date(`${date}T${start}`).toISOString();let endDate=new Date(`${date}T${end}`);if(endDate.getTime()<=Date.parse(startAtUtc))endDate.setDate(endDate.getDate()+1);const item={title:document.querySelector('#event-title').value.trim(),description:document.querySelector('#event-description').value.trim(),startAtUtc,endAtUtc:endDate.toISOString(),category:document.querySelector('#event-category').value,desiredPublication:{local:true,twitch:document.querySelector('#event-category').value==='live',google:false}};if(!state.runtime){state.planning.unshift({day:'Démo',time:start,title:item.title,kind:item.category==='live'?'Twitch':item.category});document.querySelector('#event-dialog').close();render();return}try{await request('/api/v1/planning',{method:'POST',body:JSON.stringify(item)});document.querySelector('#event-dialog').close();event.currentTarget.reset();await refreshRuntime();toast('Événement ajouté')}catch(error){toast(error.message,true)}};
document.querySelectorAll('[data-close-dialog]').forEach(button=>button.onclick=()=>document.querySelector(`#${button.dataset.closeDialog}`).close());
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});
document.querySelector('#mode').onclick=async e=>{state.runtime=!state.runtime;e.currentTarget.textContent=state.runtime?'Runtime':'Démo';document.querySelector('.preview-mode span').textContent=state.runtime?'APERÇU · RUNTIME PC':'APERÇU · AUCUNE COMMANDE RÉELLE';runtimeUi(state.runtime,state.runtime?'Connexion au Runtime…':'Aucune commande réelle');if(state.runtime)await refreshRuntime();else{state.scene=fixture.live.scene;state.sounds=structuredClone(fixture.sounds);state.audio=structuredClone(fixture.audio);state.live=structuredClone(fixture.live);state.planning=structuredClone(fixture.planning);render()}toast(state.runtime?'Mode Runtime activé':'Mode Démo activé')};
window.addEventListener('keydown',e=>{if(e.altKey&&['1','2','3','4'].includes(e.key)){e.preventDefault();state.view=['home','live','sounds','planning'][+e.key-1];render()}});
setInterval(()=>{if(state.runtime&&state.timerRunning){state.seconds=Math.max(0,state.seconds-1);if(state.view==='live')render()}},1000);
render();runtimeUi(false,'Aucune commande réelle');
