import { fixture } from './fixtures.js';
const state={view:'home',runtime:false,scene:fixture.live.scene,timerRunning:true,seconds:36,sounds:fixture.sounds,audio:fixture.audio};
const view=document.querySelector('#view'),title=document.querySelector('#title'),eyebrow=document.querySelector('#eyebrow');
const commandLog=[]; window.__preview={state,commandLog};
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function send(type,payload={}){commandLog.push({type,payload});if(state.runtime)fetch('/api/v1/commands',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({commandId:crypto.randomUUID(),type,origin:'desktop',issuedAt:new Date().toISOString(),payload})}).catch(()=>toast('Runtime indisponible'));}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1300)}
const scenes=()=>`<div class="scene-grid">${fixture.scenes.map(name=>`<button class="scene ${state.scene===name?'active':''}" data-scene="${name}" aria-pressed="${state.scene===name}">${name}</button>`).join('')}</div>`;
const sounds=()=>Object.entries(state.sounds.reduce((groups,s)=>{(groups[s.category]??=[]).push(s);return groups},{})).map(([category,items])=>`<div class="group"><h3>${esc(category)}</h3><div class="pads">${items.map(s=>`<button class="pad ${s.sourceAvailable?'':'missing'}" data-sound="${esc(s.id)}" ${s.enabled?'':'disabled'}>${esc(s.name)}${s.sourceAvailable?'':' · absent'}</button>`).join('')}</div></div>`).join('');
function home(){return `<div class="stack"><section class="status-strip"><div><span class="live-pill">● LIVE</span><strong class="value">${fixture.live.duration}</strong><span class="label">${fixture.live.title} · ${fixture.live.category}</span></div><div><span class="label">Viewers</span><b class="value">17</b></div><div><span class="label">Chat</span><b class="value">6</b></div><div><span class="label">OBS</span><b>Connecté</b></div><div><span class="label">Twitch</span><b>En direct</b></div></section><section class="section"><div class="section-head"><h2>Scènes principales</h2><span class="label">Active · ${state.scene}</span></div>${scenes()}</section><section class="section"><div class="section-head"><h2>Sons rapides</h2><button class="secondary" data-add-sound>+ Ajouter un son rapide</button></div><div class="sound-groups">${sounds()}</div></section></div>`}
function live(){return `<div class="cockpit"><section class="status-strip wide"><div><span class="live-pill">● LIVE</span><b class="value">02:14:32</b></div><div><span class="label">Viewers</span><b class="value">17</b></div><div><span class="label">Chat</span><b class="value">6</b></div><div><span class="label">Scène</span><b>${state.scene}</b></div><div><button class="critical" data-live-stop>Arrêter le live</button></div></section><section class="section wide"><div class="section-head"><h2>Scènes</h2></div>${scenes()}</section><section class="section"><div class="section-head"><h2>Audio</h2><span class="label">Sources actives</span></div>${state.audio.map((a,i)=>`<div class="audio-row"><b>${a.name}${a.primary?' · principal':''}</b><button data-mute="${i}" aria-label="${a.muted?'Réactiver':'Couper'} ${a.name}">${a.muted?'OFF':'ON'}</button><div class="meter"><i style="width:${a.level}%"></i></div><span>${a.volume}%</span></div>`).join('')}</section><section class="section timer"><div class="section-head"><h2>Timer</h2></div><b class="timer-value">00:${String(state.seconds).padStart(2,'0')}:00</b><div class="timer-actions"><button class="action" data-timer="minus">−1 min</button><button class="action" data-timer="toggle">${state.timerRunning?'Pause':'Play'}</button><button class="action" data-timer="plus">+1 min</button><button class="action" data-timer="reset">Reset</button></div></section></div>`}
function soundboard(){return `<section class="section"><div class="section-head"><div><h2>Soundboard</h2><span class="label">OBS Soundboard · prêt · une lecture à la fois</span></div><div><button class="secondary" data-obs-setup>Configurer dans OBS</button> <button class="critical" data-stop>Stop</button></div></div><div class="toolbar"><input type="search" placeholder="Rechercher un son" aria-label="Rechercher un son"><button class="action" data-add-sound>+ Ajouter un son</button></div><div class="sound-groups">${sounds()}</div></section>`}
function planning(){return `<section class="section"><div class="section-head"><div><h2>Semaine</h2><span class="label">18 — 24 septembre</span></div><button class="action" data-add-event>+ Nouvel événement</button></div><div class="agenda">${fixture.planning.map(e=>`<button class="event"><b>${e.day}</b><span>${e.time}</span><strong>${e.title}</strong><span class="kind">${e.kind}</span></button>`).join('')}</div></section>`}
const campItems=['Préparation','Notes','Templates','Soutiens','Automatisations','Médias OBS','Connexions','Diagnostics','Réglages'];
function camp(){return `<div class="camp-grid"><section class="section camp-nav">${campItems.map((x,i)=>`<button class="${i===0?'active':''}" data-camp="${x}">${x}</button>`).join('')}</section><section class="section empty-detail"><p class="eyebrow">LE CAMP</p><h2 id="camp-title">Préparation</h2><p id="camp-copy">Checklist avant direct · 4 éléments terminés sur 6.</p></section></div>`}
function render(){const names={home:['Accueil','COCKPIT'],live:['Live','EN DIRECT'],sounds:['Sons','BIBLIOTHÈQUE'],planning:['Planning','SEMAINE'],camp:['Le Camp','SECONDAIRE']};[title.textContent,eyebrow.textContent]=names[state.view];view.innerHTML=({home,live,sounds:soundboard,planning,camp}[state.view])();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',b.dataset.view===state.view?'page':'false'));bind()}
function bind(){document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{state.scene=b.dataset.scene;send('obs.scene.set',{sceneName:state.scene});toast(`Scène ${state.scene}`);render()});document.querySelectorAll('[data-sound]').forEach(b=>b.onclick=()=>{send('soundboard.play',{soundId:b.dataset.sound});b.classList.add('playing');toast(`${b.textContent} envoyé à OBS`)});document.querySelectorAll('[data-mute]').forEach(b=>b.onclick=()=>{const a=state.audio[+b.dataset.mute];a.muted=!a.muted;send('obs.audio.mute',{inputName:a.name,muted:a.muted});render()});document.querySelectorAll('[data-timer]').forEach(b=>b.onclick=()=>{const action=b.dataset.timer;if(action==='toggle')state.timerRunning=!state.timerRunning;if(action==='plus')state.seconds++;if(action==='minus')state.seconds=Math.max(0,state.seconds-1);if(action==='reset'){state.seconds=0;state.timerRunning=false}send(`timer.${action}`);render()});document.querySelector('[data-stop]')?.addEventListener('click',()=>{send('soundboard.stop');toast('Lecture arrêtée')});document.querySelectorAll('[data-add-sound],[data-add-event],[data-obs-setup],[data-live-stop]').forEach(b=>b.onclick=()=>toast('Dialogue disponible en mode Runtime'));document.querySelectorAll('[data-camp]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-camp]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#camp-title').textContent=b.dataset.camp;document.querySelector('#camp-copy').textContent=b.dataset.camp==='Diagnostics'?'Build b4e6006 · Runtime actif · OBS WS connecté · stateRevision 128':'Cet outil reste accessible sans encombrer le cockpit.'})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelector('#mode').onclick=e=>{state.runtime=!state.runtime;e.currentTarget.textContent=state.runtime?'Runtime':'Démo';document.querySelector('.preview-mode span').textContent=state.runtime?'APERÇU · RUNTIME PC':'APERÇU · AUCUNE COMMANDE RÉELLE';toast(state.runtime?'Mode Runtime activé':'Mode Démo activé')};window.addEventListener('keydown',e=>{if(e.altKey&&['1','2','3','4'].includes(e.key)){e.preventDefault();state.view=['home','live','sounds','planning'][+e.key-1];render()}});render();
