import { filterPlanning, weekAgenda } from './planning-model.js';
const WIDTH=1080,HEIGHT=1350;
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function header(ctx,streamer,weekly){const g=ctx.createLinearGradient(0,0,WIDTH,HEIGHT);g.addColorStop(0,'#090914');g.addColorStop(.6,'#18112c');g.addColorStop(1,'#321827');ctx.fillStyle=g;ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#bca8ff';ctx.font='700 26px system-ui';ctx.fillText('LE FEU DE CAMP',70,72);ctx.fillStyle='#fff';ctx.font='800 58px system-ui';ctx.fillText(weekly?'AGENDA DE LA SEMAINE':'AUJOURD’HUI EN LIVE',70,142);ctx.fillStyle='#aaa2bb';ctx.font='500 24px system-ui';ctx.fillText(streamer,72,184);}
function eventLine(ctx,item,y){const time=new Date(item.startAtUtc).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});ctx.fillStyle='#ffbd85';ctx.font='900 35px system-ui';ctx.fillText(time,95,y);ctx.fillStyle='#fff';ctx.font='750 27px system-ui';ctx.fillText(String(item.title||'Live').slice(0,34),260,y);ctx.fillStyle='#bca8ff';ctx.font='600 20px system-ui';ctx.textAlign='right';ctx.fillText(String(item.twitchCategoryName||'').slice(0,25),970,y);ctx.textAlign='left';}
function note(ctx,value){if(!value)return;ctx.fillStyle='#aaa2bb';ctx.font='italic 22px system-ui';ctx.fillText(String(value).slice(0,78),70,1290);}
export async function exportPlanningImage(items,streamerName='StreamDashboard',options={}){const weekly=options.period==='next-week';const canvas=document.createElement('canvas');canvas.width=WIDTH;canvas.height=HEIGHT;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas indisponible.');header(ctx,streamerName,weekly);let count=0;
if(weekly){const days=weekAgenda(items,options.filters);days.forEach((day,index)=>{const y=220+index*143;rounded(ctx,60,y,960,125,22);ctx.fillStyle=index%2?'rgba(255,255,255,.055)':'rgba(150,105,235,.09)';ctx.fill();ctx.fillStyle='#cdbaff';ctx.font='800 25px system-ui';ctx.fillText(day.date.toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long'}).toUpperCase(),85,y+34);if(!day.events.length){ctx.fillStyle='#797286';ctx.font='500 24px system-ui';ctx.fillText('Pas de live',85,y+82);}else{day.events.slice(0,2).forEach((item,i)=>eventLine(ctx,item,y+76+i*34));count+=day.events.length;}});}else{const events=filterPlanning(items,options.filters,'today');if(!events.length)throw new Error('Aucun live aujourd’hui à exporter.');events.slice(0,5).forEach((item,index)=>{const y=245+index*175;rounded(ctx,60,y,960,150,25);ctx.fillStyle='rgba(255,255,255,.07)';ctx.fill();eventLine(ctx,item,y+62);ctx.fillStyle='#ddd7e7';ctx.font='500 23px system-ui';ctx.fillText(new Date(item.startAtUtc).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}),95,y+112);});count=events.length;}
note(ctx,options.noteEnabled?options.noteText:'');ctx.fillStyle='#6f687e';ctx.font='500 18px system-ui';ctx.fillText('Planning prévisionnel · StreamDashboard',70,1325);const blob=await new Promise((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error('Export PNG impossible.')),'image/png'));const file=new File([blob],`planning-${weekly?'semaine':'aujourdhui'}.png`,{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Planning des lives'});return count;}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return count;}
