import { describe, expect, it } from 'vitest'; import request from 'supertest'; import { createApp } from '../src/api/app.js'; import { SequenceEngine } from '../src/sequences/engine.js'; import type { ObsGateway, Profile } from '../src/types.js';
const profile:Profile={id:'dam',name:'Dam',theme:'campfire',modes:{intro:{text:'INTRO',durationSeconds:300,timerVisible:true},pause:{text:'PAUSE',durationSeconds:600,timerVisible:true},end:{text:'END',durationSeconds:90,timerVisible:false}},scenes:{intro:'INTRO',pause:'PAUSE',end:'FIN',afterIntro:'LIVE'},options:{autoStartStreaming:false,autoSwitchAfterIntro:true,autoReturnAfterPause:true}};
class FakeObs implements ObsGateway{connected=true;currentScene:string|null='LIVE';streaming=true;async setScene(n:string){this.currentScene=n}async setSceneAndWait(n:string){await this.setScene(n)}async getCurrentScene(){return this.currentScene!}async startStreaming(){this.streaming=true}async stopStreaming(){this.streaming=false}}
const setup=()=>{const obs=new FakeObs(),engine=new SequenceEngine(profile,obs);return{obs,engine,app:createApp(engine)}};
describe('API and sequences',()=>{
it('gets fail-safe idle state',async()=>{const{app}=setup();const r=await request(app).get('/api/state');expect(r.body).toMatchObject({mode:'idle',running:false,timerVisible:false})});
it('starts intro and treats a double click idempotently',async()=>{const{app,engine}=setup();await request(app).post('/api/intro/start').expect(200);const seq=engine.state().sequence;await request(app).post('/api/intro/start').expect(200);expect(engine.state()).toMatchObject({mode:'intro',timerVisible:true,sequence:seq})});
it('returns from pause to the remembered scene',async()=>{const{app,obs}=setup();await request(app).post('/api/pause/start').expect(200);expect(obs.currentScene).toBe('PAUSE');await request(app).post('/api/pause/return').expect(200);expect(obs.currentScene).toBe('LIVE')});
it('runs end internally without exposing its timer and can cancel',async()=>{const{app,engine,obs}=setup();await request(app).post('/api/end/start').expect(200);expect(engine.state()).toMatchObject({mode:'end',running:true,timerVisible:false});await request(app).post('/api/end/cancel').expect(200);expect(obs.streaming).toBe(true);expect(obs.currentScene).toBe('LIVE')});
it('supports timer controls',async()=>{const{app}=setup();await request(app).post('/api/intro/start');await request(app).post('/api/timer/add').send({seconds:60}).expect(200).expect(r=>expect(r.body.remaining).toBe(360));await request(app).post('/api/timer/pause').expect(200);await request(app).post('/api/timer/resume').expect(200);await request(app).post('/api/timer/reset').expect(200)});
it('rejects malformed JSON and invalid parameters',async()=>{const{app}=setup();await request(app).post('/api/timer/add').set('Content-Type','application/json').send('{').expect(400);await request(app).post('/api/timer/add').send({seconds:'x'}).expect(409)});
it('reports unavailable OBS clearly',async()=>{const{app,obs}=setup();obs.connected=false;await request(app).post('/api/intro/start').expect(503).expect({error:'OBS WebSocket is unavailable'})});
it('rejects impossible commands',async()=>{const{app}=setup();await request(app).post('/api/pause/return').expect(409)});
it('SSE sends the complete current state immediately',async()=>{const{engine}=setup();await engine.start('intro');let data='';const listener=(s:unknown)=>data=JSON.stringify(s);engine.on('state',listener);listener(engine.state());expect(JSON.parse(data)).toMatchObject({mode:'intro',remaining:300})});
it('handles intro, pause, and end expiration actions',async()=>{let now=Date.now();const obs=new FakeObs();const engine=new SequenceEngine(profile,obs,()=>now);await engine.start('intro');now+=301000;await (engine as any).expire();expect(obs.currentScene).toBe('LIVE');await engine.start('pause');now+=601000;await (engine as any).expire();expect(obs.currentScene).toBe('LIVE');await engine.start('end');now+=91000;await (engine as any).expire();expect(obs.streaming).toBe(false);expect(engine.state().mode).toBe('idle')});
});
